language: generic

sudo: false
cache:
  directories:
  - "$HOME/.racket"
env:
  global:
  - RACKET_DIR=~/racket
  - RACKET_VERSION=6.12
  - secure: lOEOMCE8Eks+9VEB/PFd0e+nQPLAy4I2JhLAjJ2jQCzV7D06jA+/kY7bSeiW/irgDHXG7CWYJgWn7p1n7RtXdYIq6PtjQox2eETkVmnWEL9dcVz11iNB4l37G9rC1RZuSccwJ2eJGLUr3qsOD8yU/yecAij9BjuZ3Wgicm6rehpqfXtDYe87YvIEUxAFAsOFbVc+14xsKBTquUqW7f+A580PLTCQAWj93YcZ8zP1iaXlqeEVNnkjWK7ZegWNUdD94IlnFCUL1EmVSX+bBS2P9T1Ddk5DgYjhdc8DFLstkjDkQYxls1xQ5LW5rzAgjwNEoCsC/5MHTjDjhBsLKABJ7TuARL0jkkb7KHayfN0AH1XmuHPZ7ZylY/DKuFWTHoJGnyHwbhG7Ng5oPRhOec8PU4JjpJWCNLHWmSVZ5Oj9Qc/B3FUZAFWU+o4yGIuI6P5unBRmoDFuEoNuT5trkjknGaInhrpYMSFo1CjCOBT0XXmwfkZeOlkNAEJtSvq2ENIAbQ1enfJ33xeVdYOc0ZnIEjRXzYs50ncAYMhFBnfA3+BCJhMrMzdXtK190nhzpCQJHGQo69JDy8lblxvDzDl7ZlI0mI4D3XqdzxtzaE7kYiJ6T/NAVxVepQUxy0gcwbNLp29VnQlcv4NMew2n6BRjoIVad30UWqsSte15oITanNQ=

addons:
  apt:
    packages:
    - python-pygments
    - fonts-linuxlibertine

before_install:
- "./install-racket.sh"
- export PATH="${RACKET_DIR}/bin:${PATH}"
install:
- racket website.rkt -db && cd $TRAVIS_BUILD_DIR
script:
- echo 0
deploy:
  skip_cleanup: true
  provider: script
  script: "./deploy.sh"
  on:
    branch: master
